# Generated by Django 5.2.1 on 2025-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_alter_buyer_credit_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_purchased',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
